name: doctor_app_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  get: ^4.7.0
  flutter_credit_card: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2 

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "0xffFFFFFF"
  image_path: "assets/images/app_logo.png"  

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash_screen/
    - assets/images/onboarding_screen/
    - assets/images/home_screen/
    - assets/images/home_screen/live_doctor/
    - assets/images/home_screen/popular_doctor/
    - assets/images/home_screen/feature_doctor/
    - assets/images/home_screen/category/
    - assets/images/live_doctor_screen/
    - assets/images/find_doctor_screen/
    - assets/images/select_time_screen/
    - assets/images/popular_screen/
    - assets/images/favorite_screen/
    - assets/images/profile_screen/
    - assets/images/auth_image/
    - assets/images/medicine_screen/
    - assets/images/medicine_screen/medicines/
    - assets/images/bg/